### ISSUE TITLE
Parameter with typing

### ISSUE THREAD

**Issue by WheheoHu** [mrocklin/multipledispatch#123]
my code have two classes
`ClassA` and `ClassB`
I want to dispatch 
```python
@dispatch(List[ClassA])
def func(self, class_list):
    dosomewithClassA()
@dispatch(List[ClassB])
def func(self, class_list):
    dosomewithClassB()
```

but i got `TypeError: Parameterized generics cannot be used with class or instance checks`

**Comment by ice-tong** [comment]
[plum](https://github.com/wesselb/plum) is all you need!

**Comment by Wouter1** [comment]
>[plum](https://github.com/wesselb/plum) is all you need!
Ok thanks for the suggestion. Is multipledispatch dead or why is this issue ignored?

**Comment by mrocklin** [comment]
I'm not actively maintaining this library any longer.  If others want to step up they are welcome to do so.

**Comment by Wouter1** [comment]
@mrocklin thanks for the clarification!
