### ISSUE TITLE
Add support for dispatching to descriptors

### ISSUE THREAD

**Issue by justanr** [mrocklin/multipledispatch#57]
Consider this example:

``` python
from multipledispatch import dispatch

class Frob(object):
    @dispatch(int)
    @classmethod
    def bar(cls, things):
        ...
```

Will fail with `AttributeError: 'classmethod' object has no attribute '__name__'`, similarly with `staticmethod` and any other descriptor that doesn't proxy access to `__name__` (`property` aside)

There's a few ways to address this issue:
1. The simple and easy way: Simply type check for classmethod and staticmethod. There's nothing wrong with this, unless someone uses their own descriptors (say a caching/memoizing descriptor). In which case, they're out of luck for using multiple dispatch with it.
2. [The extendable but slightly questionable way](https://github.com/justanr/objtoolz/blob/68aee9a932f8bbf1b120a5da200368feec5258c5/objtoolz/descriptors/undescriptor.py) -- this works, as I implemented [`functools.singledispatch`](https://github.com/justanr/objtoolz/blob/68aee9a932f8bbf1b120a5da200368feec5258c5/objtoolz/descriptors/singledispatch.py) as a descriptor using this method however, it chokes on `staticmethod` in Python 2.7 (due to the bound/unbound distinction there).
3. The middleground where a registry of allowed descriptors is kept.  **Pros:** Check just becomes `isinstance(method, one_these_descriptor_types)` and it won't choke on unraveling staticmethod. **Cons:** Global state or passing a registry to dispatch and it's subordinates.

**Comment by mrocklin** [comment]
Global state doesn't concern me that much in this case because it's really just a registry of how to do things correctly.  It's unlikely that two sources will disagree about how to get the name out of a classmethod.

**Comment by justanr** [comment]
I'll start putting a PR together.

**Comment by mrocklin** [comment]
The simple and easy way would also be fine by me by the way.  I don't have strong opinions here as long as it's easy to maintain, doesn't hurt performance, and gets the immediate job done.  It's entirely possible that a long chain of if-statements satisfies these requirements.
