### ISSUE TITLE
str vs unicode

### ISSUE THREAD

**Issue by xarx00** [mrocklin/multipledispatch#68]
I've got problems with make working `@dispatch(str)`. It doesn't match unicode strings, while `@dispatch(str)` doesn't match ordinary strings :-(. Perhaps a virtual type that would match both would be helpful in this common case.

**Comment by mrocklin** [comment]
Multipledispatch just uses python typing, and in particular the `issubclass` function to determine when signatures match.  As a result, normal intuition from Python carries over.  You probably want `@dispatch((str, unicode))`.
