### ISSUE TITLE
Cutting a release

### ISSUE THREAD

**Issue by mariusvniekerk** [mrocklin/multipledispatch#73]
There have been quite a few improvements in multipledispatch since the last release.  
Is it time to make a 0.4.10 / 0.5.0 with the import time improvements and basic py3 type annotation support?

@mrocklin @llllllllll

**Comment by mrocklin** [comment]
Happy to do a release if desired

**Comment by mariusvniekerk** [comment]
would be much appreciated

**Comment by mrocklin** [comment]
@llllllllll any objection or concern?

**Comment by llllllllll** [comment]
No, actually @ssanderson was harassing me to get multipledispatch updated in our own code. A release sounds great.

**Comment by ssanderson** [comment]
:sparkling_heart:

**Comment by mrocklin** [comment]
0.5.0 is on PyPI
