### ISSUE TITLE
Keyword-argument dispatch

### ISSUE THREAD

**Issue by hameerabbasi** [mrocklin/multipledispatch#81]
Hello. I ran into needing keyword-argument dispatch in [my own project ](https://github.com/hameerabbasi/arrayish)(although it's hardly a project, more a wrapper around Numpy and multipledispatch).

I need to override Numpy functions of the form `func(arg1, arg2, kwarg1=default1, kwarg2=default2)` (as an example).

Fortunately, I can write separate signatures that accept 2, 3 or 4 arguments.

Unfortunately, these will ignore the types of keyword-arguments, and it needs three signatures to work.

So, here is the API I propose (feel free to discuss)

```python
from multipledispatch import Dispatcher

func1 = Dispatcher('func1')

def func1_default(arg1, arg2, kwarg1=default1, kwarg2=default2)
    pass

func1_dispatcher.add((type1, type2, ('kwarg1', type3), ('kwarg2', type4)), func1_default)
```
Or,

```python
from multipledispatch import dispatch

@dispatch(type1, type2, ('kwarg1', type3), ('kwarg2', type4))
def func1(arg1, arg2, kwarg1=default1, kwarg2=default2)
    pass
```

I would have liked something like the following, but unfortunately, it isn't possible due to `dict`s being unordered in Python < 3.6 and even in 3.6 it being an implementation detail rather than a documented feature:

```python
from multipledispatch import dispatch

@dispatch(type1, type2, kwarg1=type3, kwarg2=type4)
def func1(arg1, arg2, kwarg1=default1, kwarg2=default2)
    pass
```

CC-ing interested parties:

- @shoyer for XArray, which might ultimately need Arrayish.
- @mrocklin for Dask, which might ultimately need Arrayish.
- @mrocklin Once again, to ping more interested parties.
- And, of course, me for [pydata/sparse](https://github.com/pydata/sparse) and [Arrayish](https://github.com/hameerabbasi/arrayish).

If someone is willing to point me to code, I'll try my hand at a PR if I understand anything. 😅

**Comment by hameerabbasi** [comment]
I also recommend some sentinels (unless something similar is already in Python?)

- `NonPositional` (means the `kwarg` is not positional, but part of `**kwargs`).
  - This is to make sure argument cannot be passed in a positional way.
- `Required` (means it's a positional argument, but with a name)
  - For usage like `func(arg1=value1)` where `arg1` is positional.

All unspecified kwargs are passed through unchanged. So, for the following function:

```python
def func1_default(arg1, kwarg1=default1, **kwargs)
    kwargs.pop('kwarg2', default2)
```

We would have the signature:

```python
((type1, Required), ('kwarg1', type2), ('kwarg2', type3, NonPositional))
```

**Comment by hameerabbasi** [comment]
Ah, I just realized (by reading the source code) that this project is using tuples as unions of types. So I suggest the following for the above function:

```
(RequiredArgument(type1, name='arg1'), KeywordArgument(type2, name='kwarg1'), KeywordArgument(type3, name='kwarg2'))
```

I just realized that it isn't necessary to have `NonPositional`, the function will err anyway.

**Comment by Po-Hsuan-Huang** [comment]
https://stackoverflow.com/a/8655544

**Comment by hameerabbasi** [comment]
This was sorted by array function and uarray -- closing.
