### ISSUE TITLE
License file in pypi archive

### ISSUE THREAD

**Issue by toddrme2178** [mrocklin/multipledispatch#82]
The pypi source archive isn't including the `LICENSE.txt` file. Would it be possible to add it? It is very helpful when packaging this for Linux distributions. Thank you.

**Comment by tswast** [comment]
Looks like if I build with `python setup.py bdist_wheel` with a recent version of the wheel package it is now included. Might just need a point release and a push.

**Comment by mrocklin** [comment]
I'll spend ten minutes and try to bring this repository slightly more into
modern times.

**Comment by tswast** [comment]
Thanks! Looks like it worked.

```
$ ls env/lib/python3.10/site-packages/multipledispatch-1.0.0.dist-info/
INSTALLER  LICENSE.txt  METADATA  RECORD  REQUESTED  top_level.txt  WHEEL
```

**Comment by mrocklin** [comment]
Grand.  Closing.
