### ISSUE TITLE
Pickable dispatched functions

### ISSUE THREAD

**Issue by dycw** [mrocklin/multipledispatch#94]
Hi,

I would love to know how one can make these functions pickleable?

**Comment by llllllllll** [comment]
I realize this is somewhat stale, but pickling functions can be somewhat tricky. Are you trying to pickle the functions for use in a distributed computation library like Dask? If so, you might want to look at the [cloudpickle](https://github.com/cloudpipe/cloudpickle/) project. It might be able to pickle dispatched functions right out of the box, but I haven't checked.

**Comment by dycw** [comment]
I will check it out - thank you.
