### ISSUE TITLE
drop 3.3

### ISSUE THREAD

**Issue by llllllllll** [mrocklin/multipledispatch#99]
It looks like coverage doesn't work with 3.3 anymore due to pkg_resources: https://travis-ci.org/mrocklin/multipledispatch/jobs/488671902

This is blocking any new PRs because of the travis builds. Should we try to work around this or remove 3.3 from the travis matrix?

**Comment by mrocklin** [comment]
Happy to have 3.3 removed.

**Comment by llllllllll** [comment]
Great, I will add that to the linked PR.
